### PR TITLE
fix(deps): update to graphql@15

### LINKED ISSUE #298: graphql 15 compatibilty
Is this package fully compatible with v15 of https://www.npmjs.com/package/graphql?
If yes then peerDependencies should be updated to include it.

### PR DESCRIPTION
**Pull request by adriencohen**
Closes #298

### CODE REVIEW

**Comment by zefexdeveloper** [comment]
bump

**Comment by barbieri** [comment]
bump

**Comment by airhorns** [comment]
It'd be really great to get this in!

**Comment by tunegov** [comment]
Bump

**Pull request merged**
