### PR TITLE
Include src for source maps

### PR DESCRIPTION
**Pull request by maclockard**
fixes https://github.com/apollographql/graphql-tag/issues/389

### CODE REVIEW

**Comment by maclockard** [comment]
@hwillson mind taking a look at this?

**Review by benjamn — APPROVED** [review]
@maclockard I have no problem with publishing the `src/` directory. Do you think this PR by itself will make source maps work as you hoped, or are there any other necessary steps?

**Comment by maclockard** [comment]
I believe its all that's needed since y'all already publish source maps with correct paths!

**Comment by maclockard** [comment]
@benjamn how do I get the build tests to run against this PR?

**Pull request merged**
