### PR TITLE
Add `yarn.lock`, `.editorconfig`, and `.flowconfig` to `.npmignore`.

### PR DESCRIPTION
**Pull request by wtgtybhertgeghgtwtg**
Alternatively, you could use the `files` field in `package.json` to whitelist the stuff you do want to push to NPM.

### CODE REVIEW

**Comment by stubailo** [comment]
I can see why this might be nice, but what's the actual benefit for users of the library?

**Comment by wtgtybhertgeghgtwtg** [comment]
Just a slightly shorter install time.  The size of the package would be cut by about a third.  If you add `test` and `.github` to it, that bumps up to about a half.

**Comment by stubailo** [comment]
OK I can see how `yarn.lock` could be pretty huge.

**Comment by stubailo** [comment]
Thanks!

**Pull request merged**
