### PR TITLE
Implement ES6 export file

### LINKED ISSUE #303: Implement ES6 export file
Angular worked on the build process in v10 and removed support for already transpiled code to ES5 for Angular Libraries. Also they now show a warning for every dependency that is imported in ES5.

More information:
https://angular.io/guide/build#configuring-commonjs-dependencies

Example warning:

```
WARNING in P:\XXX\XXX.js depends on graphql-tag. CommonJS or AMD
 dependencies can cause optimization bailouts.
```

To avoid this we'd need an ES6 file in "main" property of package.json or at least a file in the `lib` folder in ES6 that can be imported directly. This should be the feature request of this issue.

### PR DESCRIPTION
**Pull request by PowerKiKi**
This upgrade all dev dependencies in order to implement ES6 exports
in order to solve #303.

This also remove yarn.lock entirely because this package is meant to
work with npm only as can be seen from the mention of npm command in
package.json.

Fixes #303
Closes #272
Closes #273

### CODE REVIEW

**Comment by PowerKiKi** [comment]
This PR is mostly a rebase of #273

**Comment by matthewerwin** [comment]
What's the hangup on getting this merged?

**Comment by PowerKiKi** [comment]
@benjamn may I asked you to either review yourself or assign a reviewer please ?

Both this PR and #273 should be relatively quick to review as there is no logic changes in the package itself. It's mostly configuring the tools properly. And I believe it would be a welcome change for the community.

**Comment by benjamn** [comment]
@PowerKiKi Thanks for the ping! I recently got my GitHub notifications under control(-ish), so hopefully I won't miss stuff like this in the future.

@hwillson Any thoughts/recollections as to why we hadn't done this before? Was it just that we wanted to convert the package to TypeScript first?

**Comment by hwillson** [comment]
> Was it just that we wanted to convert the package to TypeScript first?

Exactly!

**Comment by benjamn** [comment]
Another ESM-incompatible npm package used by `@apollo/client` that we're updating/wrapping to be more ESM-friendly: https://github.com/apollographql/apollo-client/pull/7615

**Review by benjamn — APPROVED** [review]
Thanks for getting this started @PowerKiKi, and please let us know if you have any concerns about the additional commits that I pushed.

**Comment by PowerKiKi** [comment]
Thank you for merging this.

I would like to emphasize that all credits should go to @abdonrd :tada:  . I merely rebased his work.

**Comment by abdonrd** [comment]
Thanks for the mention @PowerKiKi!

**Pull request merged**
