### PR TITLE
Update all the dependencies

### PR DESCRIPTION
**Pull request by abdonrd**
Update all the dependencies to the latest versions.

### CODE REVIEW

**Comment by abdonrd** [comment]
Friendly ping to @jnwng 😄

**Comment by jnwng** [comment]
looks good to me! one last thing i need to validate is the `yarn.lock` changes — as much as i trust you, i actually realize i have no way to validate security vulnerabilities that might have been introduced

**Comment by abdonrd** [comment]
Ok! I just run `rm -rf node_modules yarn.lock; yarn install`

**Comment by abdonrd** [comment]
Anything else, @jnwng? Thanks in advance!

**Comment by abdonrd** [comment]
Rebased on master!

**Comment by abdonrd** [comment]
Friendly ping to @hwillson.

**Comment by abdonrd** [comment]
Dependencies updated again!

**Comment by abdonrd** [comment]
Hi @jnwng! What happened to this PR? Thanks in advance!

**Comment by PowerKiKi** [comment]
Ideally, this should be closed in favor of #325.

**Pull request closed without merging**
