### PR TITLE
Upgrade to GraphQL 16

### PR DESCRIPTION
**Pull request by brainkim**
Adds GraphQL 16 to be added to the ranges of `graphql-tag`.

### CODE REVIEW

**Comment by sachaw** [comment]
This is a blocker for me and a number of other libraries, @benjamn @hwillson Could we please look at getting this merged.

Many thanks.

**Review by hwillson — APPROVED** [review]
Looks great - thanks @brainkim!

**Comment by hwillson** [comment]
@sachaw published as `graphql-tag@2.12.6`. Let us know if you notice any issues. Thanks!

**Comment by rafagsiqueira** [comment]
Was this ever published to npm? I don't see a release 2.12.6.

**Comment by hwillson** [comment]
@rafagsiqueira it was: https://www.npmjs.com/package/graphql-tag/v/2.12.6

**Pull request merged**
