### PR TITLE
feat(deps): Remove Printer and Parser re-exports

### PR DESCRIPTION
**Pull request by abhiaiyer91**
https://github.com/apollographql/graphql-tag/issues/49

### CODE REVIEW

**Comment by stubailo** [comment]
I think we may as well export "parse" right? Since this package depends on it anyway?

**Comment by abhiaiyer91** [comment]
Well I was thinking if we remove both and just make GraphQL a peer dependency we don't have to struggle with mantaining a version of GraphQL as a dependency in the repo and just have a peer dep. 

Imho I think its better to have the use the functions directly from GraphQL

**Comment by helfer** [comment]
I'll defer to @jnwng on this one. What would your preference be?

**Comment by jnwng** [comment]
i agree with @abhiaiyer91 - if we're not doing anything special with `print` or `parse` and just re-exporting it, seems better to have people use it upstream from `graphql` instead (presumably safe given that `graphql` is now a peer dependency).

however, this _is_ a breaking API change for anyone using either of these exported functions, and i would suggest deprecating them in a minor / patch version (1.3 or 1.2.x) and perhaps removing it entirely when we think we need to cut a new major version. this may seem a little drastic, but is a little more honest to how we're versioning the package, and at least gives people who are using `graphql-tag@^1.x.x` some heads up that something changed.

that being said, its very likely the case that a new major version is not needed or is just not even in the works, so it might be a bit until it makes sense to remove this. does the inclusion of `graphql/language/print` make it to production clients? if so, we may want to do a new major/minor version sooner rather than later. if not, sounds like it could wait.

**Comment by jnwng** [comment]
its also worth noting that [apollographql/apollo-client](https://github.com/apollographql/apollo-client) depends on this export [in a few places](https://github.com/apollographql/apollo-client/search?utf8=%E2%9C%93&q=graphql-tag%2Fprinter&type=Code), so we may need to be a bit more careful about versioning this change.

**Comment by helfer** [comment]
@jnwng yeah, that's right. I think the first thing we should make sure is that `print` can be imported from graphql-js without importing a whole bunch of other stuff (and thus increasing the bundle size). @abhiaiyer91 can you make PRs to apollo-client, react-apollo and angular-apollo that will do that? I want to first make sure the change to those repos looks good before moving ahead with this one.

**Comment by stubailo** [comment]
Yeah I think we definitely need to bump the major version of `graphql-tag` if we make this very significant change.

**Comment by jnwng** [comment]
thanks @abhiaiyer91!

**Pull request merged**
