### PR TITLE
Use Rollup to build also as ESM

### LINKED ISSUE #229: Exporting as ES Module Syntax (ESM)
Please, export `"module"` entry point in the `package.json` as ES Module Syntax (ESM).

More info about it here: https://www.pikapkg.com/about/

**How to reproduce the issue:**

Just download the package or see it at unpkg:
https://unpkg.com/graphql-tag@2.10.0/src/index.js?module.

### PR DESCRIPTION
**Pull request by abdonrd**
Fix #229

Based on #272.

### CODE REVIEW

**Comment by Tansito** [comment]
Very interested in this PR too!

**Comment by nikita-lobkov** [comment]
Any updates about ES6 module?

**Comment by PowerKiKi** [comment]
Ideally, this should be closed in favor of #325.

**Comment by PowerKiKi** [comment]
I only meant to help merge a apparently staled PR, but I didn't realize this PR was still active. So of course, feel free to merge either of them. It really does not matter to me, as long as we can release those improvements to the community.

**Comment by abdonrd** [comment]
From time to time I rebase the PR...
But the owners don't give an answer 😕

**Comment by abdonrd** [comment]
@PowerKiKi @benjamn new year, updated again!

**Comment by benjamn** [comment]
Thanks for this @abdonrd, but we're going to move ahead with #325, where I've pushed some additional commits to align this repository with our other projects (using TypeScript, mainly). If you have time to take a look at those changes, please let me know if you have any ideas/concerns!

**Pull request closed without merging**
