### PR TITLE
Compiled current version and removed maximum call stack exception

### PR DESCRIPTION
**Pull request by KordonDev**
My changes are in index.js. #40

The changes of the other files occur because I run `npm run compile`.

### CODE REVIEW

**Comment by abhiaiyer91** [comment]
@KordonDev is there a reason why we need startToken, endToken if we're trying to strip all loc fields in the AST?

**Comment by abhiaiyer91** [comment]
We have a goal of not bundling graphql printer and parser ourselves found here
https://github.com/apollographql/graphql-tag/pull/46

so lets see if we actually need the references to the tokens. if we do, then we can modify the PR here and ship the removal of our webpack bundle as well.

**Comment by KordonDev** [comment]
I'm not understanding the whole library. My goal was to remove the error and the merge request is for other people with the same issue.

So if you remove the tokens, feel free to close my merge request.

**Comment by jnwng** [comment]
@KordonDev thanks for the PR! as you mentioned, i think #46 should resolve the issue (it also removes the tokens) and takes care of removing some of the generated GraphQL modules as well - closing this PR to reflect that.

**Pull request closed without merging**
