### PR TITLE
Chore/ts infrastructure

### PR DESCRIPTION
**Pull request by JoviDeCroock**
Since we talked about splitting the typescript conversion up into multiple PR's this will be the first:

Next will be:

- [ ] convert the source to .ts
- [ ] update way of building
- [ ] retarget loader.js (dependent on previous step using the new cjs build)
- [ ] convert tests
- [ ] Remove obsolete dependencies (cleanup)

If anyone wants to help out by doing a part just respond here and I'll tag your name behind the task.

Every part will target this PR since this is the "root" so to speak

### CODE REVIEW

**Comment by JoviDeCroock** [comment]
I'll start on the next part when someone approves.

**Comment by jnwng** [comment]
this looks like a solid start, although i wonder if this should go into master just yet — i envisioned having a feature branch that everything got into such that when it got into master, everything was already typescript and we could release a new major version. 

what were you thinking re: workflow?

**Comment by JoviDeCroock** [comment]
I was thinking this as base branch and merge every pr to this one

**Comment by jnwng** [comment]
to clarify, you mean using this PR as as the base and have everything use this as the base? or should we change the base of this PR to something like `typescript` or `3.0` and have all incoming PRs on `apollographql/graphql-tag` re: typescript hit that base? that way we can get things reviewed and through onto that branch, and eventually merge that branch into master?

**Comment by jnwng** [comment]
re: getting this done better, i'd be open to syncing up, doing a code review of the existing code, and mapping out the granular parts of each of the checklist items you set out, to reduce the back and forth over github

**Comment by JoviDeCroock** [comment]
I don't mind how we do it but I would love to shorten the feedback loop a bit. I would suggset you making a branch named TS and me pointing my changes to that

**Comment by jnwng** [comment]
makes sense to me. i've created a branch called [typescript](https://github.com/apollographql/graphql-tag/tree/typescript) that can be used as a home base for the rewrite. thanks for taking this on!

over the next couple of weeks, i'll be making sure that i get back to do code reviews at most within a day for this, and i hope to contribute a bit myself. hope that's a short enough feedback loop for you.

**Comment by JoviDeCroock** [comment]
Thank you so much @jnwng. So this is ready for merge?

**Comment by jnwng** [comment]
apologies — thought this got merged into the branch already. are the other parts already finished?

**Pull request merged**
