### PR TITLE
Add DocumentNode to gql declaration

### PR DESCRIPTION
**Pull request by kamilkisiela**
**Pull Request Labels**

- [x] feature
- [ ] blocking
- [ ] docs

### CODE REVIEW

**Comment by yordis** [comment]
@kamilkisiela what was what I did on https://github.com/apollographql/graphql-tag/pull/193 😄

**Comment by jnwng** [comment]
Thank you both! I don’t know much about Typescript, is this a breaking
change?

**Comment by yordis** [comment]
@jnwng no, this would actually help people to remove the `any` type and have better typing support.

**Comment by kamilkisiela** [comment]
It's not, `DocumentNode` is a part of `graphql` since a long time and if someone uses TypeScript and `graphql` he has a proper type definitions for that too.

**Comment by jnwng** [comment]
btw @kamilkisiela @yordis i _thought_ i had seen this before — this was previously introduced by #141 and subsequently had to be reverted because this _is_ a [breaking change](#150)

i'm not going to release this just yet — while im not afraid of cutting a major version here, i could use some help understanding why this a breaking change at all given that both of you mentioned that it isn't. any helpful information for TypeScript users here will help us head off unnecessary pain.

**Pull request merged**
